version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "disabled"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/web.back"
    schedule:
      interval: "disabled"
    open-pull-requests-limit: 0
